fixing some omissions in workflow

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -7,6 +7,7 @@ on:
   pull_request:
     branches:
       - main
+
 jobs:
   build:
     runs-on: windows-latest
@@ -14,11 +15,19 @@ jobs:
       - name: Check out repository
         uses: actions/checkout@v2
       
+      - name: Install AutoHotkey
+        run: choco install autohotkey
+
       - name: Compile AHK Script to Executable
-        run: cmd /c '"C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe" /in Jiggler.ahk /out Jiggler.exe'
-      
-      # Your existing steps for setup, compilation, and artifact upload
-      
+        run: |
+          $AhkCompiler = "C:\ProgramData\chocolatey\lib\autohotkey\tools\Compiler\Ahk2Exe.exe"
+          if (Test-Path $AhkCompiler) {
+            & $AhkCompiler /in Jiggler.ahk /out Jiggler.exe
+          } else {
+            Write-Error "Ahk2Exe.exe not found"
+            exit 1
+          }
+
       - name: Upload artifact
         uses: actions/upload-artifact@v2
         with:
@@ -27,7 +36,7 @@ jobs:
 
   release:
     needs: build
-    runs-on: ubuntu-latest
+    runs-on: windows-latest
     steps:
       - name: Download artifact
         uses: actions/download-artifact@v2
@@ -41,12 +50,12 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          tag_name: ${{ github.ref }}
-          release_name: Release ${{ github.ref }}
+          tag_name: ${{ github.ref_name }}
+          release_name: Release-${{ github.ref_name }}-${{ github.run_number }}
           draft: false
           prerelease: false
           body: "New release of Jiggler"
-      
+
       - name: Upload Release Asset
         uses: actions/upload-release-asset@v1
         env:
