try checking at the script run

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -27,9 +27,19 @@ jobs:
       - name: Verify Extraction
         run: Get-ChildItem -Path "AutoHotkey"
 
-      - name: Compile AHK Script to Executable
+      - name: Compile AHK Script to Executable and Check Success
         run: |
-          & "${{ github.workspace }}\AutoHotkey\Compiler\Ahk2Exe.exe" /in "${{ github.workspace }}\Jiggler.ahk" /out "${{ github.workspace }}\Jiggler.exe" /verbose
+          & "${{ github.workspace }}\AutoHotkey\Compiler\Ahk2Exe.exe" /in "${{ github.workspace }}\Jiggler.ahk" /out "${{ github.workspace }}\Jiggler.exe"
+          if ($?) {
+            Write-Host "Compilation reported success"
+          } else {
+            Write-Error "Compilation reported failure"
+          }
+          if (Test-Path "${{ github.workspace }}\Jiggler.exe") {
+            Write-Host "Jiggler.exe exists."
+          } else {
+            Write-Host "Jiggler.exe does not exist."
+          }
 
       - name: Verify Compilation
         run: Get-ChildItem -Recurse
